### ISSUE TITLE
Window 10 安裝出現 UnicodeError

### ISSUE THREAD

**Issue by jboxsc163** [FutunnOpen/futuquant#140]
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\stephen\AppData\Local\Temp\pip-req-build-fl2p0333\setup.py", line 54, in <module>
        install_requires=install_requires
      File "c:\users\stephen\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\stephen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\stephen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\stephen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\stephen\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\stephen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\stephen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\stephen\appdata\local\programs\python\python36\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\stephen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\stephen\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\stephen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\build_py.py", line 53, in run
        self.build_package_data()
      File "c:\users\stephen\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\build_py.py", line 123, in build_package_data
        outf, copied = self.copy_file(srcfile, target)
      File "c:\users\stephen\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 347, in copy_file
        dry_run=self.dry_run)
      File "c:\users\stephen\appdata\local\programs\python\python36\lib\distutils\file_util.py", line 125, in copy_file
        log.info("%s %s -> %s", action, src, dir)
      File "c:\users\stephen\appdata\local\programs\python\python36\lib\distutils\log.py", line 44, in info
        self._log(INFO, msg, args)
      File "c:\users\stephen\appdata\local\programs\python\python36\lib\distutils\log.py", line 34, in _log
        stream.write('%s\n' % msg)
    UnicodeEncodeError: 'cp950' codec can't encode character '\u8ba2' in position 54: illegal multibyte sequence

**Comment by loadatom** [comment]
3.3.3已修复
