### ISSUE TITLE
network_manager MemoryError后程序卡住

### ISSUE THREAD

**Issue by July-G** [FutunnOpen/futuquant#146]
版本3.2.0
出现下面异常后程序就卡住了:
> Exception in thread Thread-610:
> Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\futuquant\common\network_manager.py", line 164, in _thread_func
>     self.poll()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\futuquant\common\network_manager.py", line 138, in poll
>     self._on_read(conn)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\futuquant\common\network_manager.py", line 322, in _on_read
>     data = conn.sock.recv(1024 * 1024)
> MemoryError

我用了两个api如下, subscribe的stock数量大约20只.
> ctx.get_stock_quote(all_stocks)
> ctx.subscribe(all_stocks, [SubType.QUOTE])

**Comment by loadatom** [comment]
尝试升级到最新版本，应该没问题了
