### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by hujb2000** [FutunnOpen/futuquant#40]
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/hujiabao/workspace_python/futuquant/futuquant/examples/TinyQuant/Run_TinyStrateSample.py
2018-01-02 19:44:14,036  INFO: FUTU	tiny_strate_sample:init_strate 'tiny_strate_sample' ret = True
('10.242.103.18', 11111)
('10.242.103.18', 11111)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/futuquant/open_context.py", line 602, in handle_read
    recv_buf = self.recv(5 * 1024 * 1024)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
BlockingIOError: [Errno 35] Resource temporarily unavailable
[Errno 35] Resource temporarily unavailable

('10.242.103.18', 11111)
('10.242.103.18', 11111)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/futuquant/open_context.py", line 602, in handle_read
    recv_buf = self.recv(5 * 1024 * 1024)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
BlockingIOError: [Errno 35] Resource temporarily unavailable
[Errno 35] Resource temporarily unavailable

('10.242.103.18', 11111)
('10.242.103.18', 11111)
('10.242.103.18', 11111)
[Errno 35] Resource temporarily unavailable

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/futuquant/open_context.py", line 602, in handle_read
    recv_buf = self.recv(5 * 1024 * 1024)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
BlockingIOError: [Errno 35] Resource temporarily unavailable
('10.242.103.18', 11111)
('10.242.103.18', 11111)
[Errno 35] Resource temporarily unavailable

('10.242.103.18', 11111)
('10.242.103.18', 11111)
[Errno 35] Resource temporarily unavailable

('10.242.103.18', 11111)
('10.242.103.18', 11111)
[Errno 35] Resource temporarily unavailable

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/futuquant/open_context.py", line 602, in handle_read
    recv_buf = self.recv(5 * 1024 * 1024)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
BlockingIOError: [Errno 35] Resource temporarily unavailable
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/futuquant/open_context.py", line 602, in handle_read
    recv_buf = self.recv(5 * 1024 * 1024)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
BlockingIOError: [Errno 35] Resource temporarily unavailable
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/futuquant/open_context.py", line 602, in handle_read
    recv_buf = self.recv(5 * 1024 * 1024)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
BlockingIOError: [Errno 35] Resource temporarily unavailable
('10.242.103.18', 11111)
('10.242.103.18', 11111)
[Errno 35] Resource temporarily unavailable

('10.242.103.18', 11111)
('10.242.103.18', 11111)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/futuquant/open_context.py", line 602, in handle_read
    recv_buf = self.recv(5 * 1024 * 1024)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
BlockingIOError: [Errno 35] Resource temporarily unavailable
[Errno 35] Resource temporarily unavailable

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/futuquant/open_context.py", line 602, in handle_read
    recv_buf = self.recv(5 * 1024 * 1024)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
BlockingIOError: [Errno 35] Resource temporarily unavailable
('10.242.103.18', 11111)
('10.242.103.18', 11111)
[Errno 35] Resource temporarily unavailable

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/futuquant/open_context.py", line 602, in handle_read
    recv_buf = self.recv(5 * 1024 * 1024)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
BlockingIOError: [Errno 35] Resource temporarily unavailable
2018-01-02 19:44:15,873  INFO: FUTU	tiny_strate_sample:on_start param1=1 param2=2
2018-01-02 19:44:16,147  INFO: FUTU	tiny_strate_sample:on_after_trading - 2018-01-02 19:44:15
('10.242.103.18', 11111)
('10.242.103.18', 11111)
[Errno 35] Resource temporarily unavailable

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/futuquant/open_context.py", line 602, in handle_read
    recv_buf = self.recv(5 * 1024 * 1024)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
BlockingIOError: [Errno 35] Resource temporarily unavailable

**Comment by FutunnOpen** [comment]
可否把能重现的脚本发我们调试一下, QQ群： 108534288

**Comment by FutunnOpen** [comment]
请使用新版本：https://www.futunn.com/download/openAPI。
