### ISSUE TITLE
ImportError: Missing required dependencies ['numpy']

### ISSUE THREAD

**Issue by alanhui1981** [FutunnOpen/futuquant#41]
I am trying to run the first example: make_order_and_cancel.py, but experience this error:
Traceback (most recent call last):
  File "C:/Users/alan/Anaconda3/Lib/site-packages/futuquant/examples/make_order_and_cancel.py", line 11, in <module>
    from futuquant.open_context import *
  File "C:\Users\alan\PycharmProjects\test\venv\lib\site-packages\futuquant\__init__.py", line 17, in <module>
    from .open_context import (
  File "C:\Users\alan\PycharmProjects\test\venv\lib\site-packages\futuquant\open_context.py", line 13, in <module>
    import pandas as pd
  File "C:\Users\alan\PycharmProjects\test\venv\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']

Process finished with exit code 1

Any hints?

**Comment by Gwill** [comment]
需要安装 pandas
