### ISSUE TITLE
MacOS Python 3.6程序无法正常结束

### ISSUE THREAD

**Issue by dr4lamb** [FutunnOpen/futuquant#61]
测试程序：
```python
from futuquant.open_context import *

#IP = '10.211.55.3'
IP = '119.29.141.202'
#IP = '192.168.31.208'
PORT = 11111
stock = 'US.BABA'

def query():
	ctx = OpenQuoteContext(IP, PORT)
	ctx.subscribe(stock, 'K_DAY')

	data = ctx.query_subscription()
	print (data)

	code, data = ctx.get_history_kline(stock, start='2018-02-07', end='2018-02-08', ktype='K_1M', autype='qfq')
	print (data)

	ctx.stop()
#	ctx.unsubscribe(stock, 'K_DAY')
	return data


if __name__ == "__main__":
	query()
	print ("Ending...")
	exit()
```

输出结果：

```
777       0.0            0.0   120791   20824238.0       -0.035  
778       0.0            0.0   258768   44536432.0       -0.121  
779       0.0            0.0  1734581  300950816.0        0.894  

[780 rows x 11 columns]
Ending...






Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/futuquant/open_context.py", line 514, in _socket_create_and_loop_connect
    self.s.connect((self.__host, self.__port))
ConnectionRefusedError: [Errno 61] Connection refused
socket connect err:ERROR. [Errno 61] Connection refused
check_sync_sock thread : exit by obj changed...
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/futuquant/open_context.py", line 514, in _socket_create_and_loop_connect
    self.s.connect((self.__host, self.__port))
ConnectionRefusedError: [Errno 61] Connection refused
socket connect err:ERROR. [Errno 61] Connection refused
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/futuquant/open_context.py", line 514, in _socket_create_and_loop_connect
    self.s.connect((self.__host, self.__port))
ConnectionRefusedError: [Errno 61] Connection refused
socket connect err:ERROR. [Errno 61] Connection refused
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/futuquant/open_context.py", line 514, in _socket_create_and_loop_connect
    self.s.connect((self.__host, self.__port))
ConnectionRefusedError: [Errno 61] Connection refused
socket connect err:ERROR. [Errno 61] Connection refused
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/futuquant/open_context.py", line 514, in _socket_create_and_loop_connect
    self.s.connect((self.__host, self.__port))
ConnectionRefusedError: [Errno 61] Connection refused
socket connect err:ERROR. [Errno 61] Connection refused
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/futuquant/open_context.py", line 514, in _socket_create_and_loop_connect
    self.s.connect((self.__host, self.__port))
ConnectionRefusedError: [Errno 61] Connection refused
socket connect err:ERROR. [Errno 61] Connection refused
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/futuquant/open_context.py", line 514, in _socket_create_and_loop_connect
    self.s.connect((self.__host, self.__port))
ConnectionRefusedError: [Errno 61] Connection refused
socket connect err:ERROR. [Errno 61] Connection refused
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/futuquant/open_context.py", line 644, in handle_read
    raise Exception("_AsyncNetworkManager : remote server close")
Exception: _AsyncNetworkManager : remote server close
_AsyncNetworkManager : remote server close

error: uncaptured python exception, closing channel <futuquant.open_context._AsyncNetworkManager 119.29.141.202:11111 at 0x110801c88> (<class 'ConnectionRefusedError'>:[Errno 61] Connection refused [/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py|read|83] [/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py|handle_read_event|420] [/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py|handle_connect_event|428])
check_sync_sock thread : exit by obj changed...


check_sync_sock thread : exit by obj changed...
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/futuquant/open_context.py", line 514, in _socket_create_and_loop_connect
    self.s.connect((self.__host, self.__port))
ConnectionRefusedError: [Errno 61] Connection refused
socket connect err:ERROR. [Errno 61] Connection refused
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/futuquant/open_context.py", line 514, in _socket_create_and_loop_connect
    self.s.connect((self.__host, self.__port))
ConnectionRefusedError: [Errno 61] Connection refused
socket connect err:ERROR. [Errno 61] Connection refused
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/futuquant/open_context.py", line 514, in _socket_create_and_loop_connect
    self.s.connect((self.__host, self.__port))
ConnectionRefusedError: [Errno 61] Connection refused
socket connect err:ERROR. [Errno 61] Connection refused
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/futuquant/open_context.py", line 514, in _socket_create_and_loop_connect
    self.s.connect((self.__host, self.__port))
ConnectionRefusedError: [Errno 61] Connection refused
socket connect err:ERROR. [Errno 61] Connection refused
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/futuquant/open_context.py", line 514, in _socket_create_and_loop_connect
    self.s.connect((self.__host, self.__port))
ConnectionRefusedError: [Errno 61] Connection refused
socket connect err:ERROR. [Errno 61] Connection refused
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/futuquant/open_context.py", line 514, in _socket_create_and_loop_connect
    self.s.connect((self.__host, self.__port))
ConnectionRefusedError: [Errno 61] Connection refused
socket connect err:ERROR. [Errno 61] Connection refused
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/futuquant/open_context.py", line 514, in _socket_create_and_loop_connect
    self.s.connect((self.__host, self.__port))
ConnectionRefusedError: [Errno 61] Connection refused
socket connect err:ERROR. [Errno 61] Connection refused
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/futuquant/open_context.py", line 644, in handle_read
    raise Exception("_AsyncNetworkManager : remote server close")
Exception: _AsyncNetworkManager : remote server close
_AsyncNetworkManager : remote server close

error: uncaptured python exception, closing channel <futuquant.open_context._AsyncNetworkManager 119.29.141.202:11111 at 0x110801c88> (<class 'ConnectionRefusedError'>:[Errno 61] Connection refused [/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py|read|83] [/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py|handle_read_event|420] [/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py|handle_connect_event|428])
check_sync_sock thread : exit by obj changed...

^CException ignored in: <module 'threading' from '/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

```

**Comment by FutunnOpen** [comment]
试下调用ctx.close()

**Comment by dr4lamb** [comment]
ctx.close()可以了，谢谢
