### ISSUE TITLE
請問remote server close 問題如果處理?

### ISSUE THREAD

**Issue by chemhong** [FutunnOpen/futuquant#66]
連線一定時長後便會出現 remote server close 問題, 我應該如何連接才會穩定一點?

**Comment by chemhong** [comment]
n_context.py", line 466, in network_query
    recv_buf = self.s.recv(5 * 1024 * 1024)
Exception: _AsyncNetworkManager : remote server close
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
_AsyncNetworkManager : remote server closewait to connect futunn plugin server


Traceback (most recent call last):
  File "C:\Python 3.5\lib\site-packages\futuquant\open_context.py", line 644, in handle_read
    raise Exception("_AsyncNetworkManager : remote server close")
Exception: _AsyncNetworkManager : remote server close
_AsyncNetworkManager : remote server close

Traceback (most recent call last):
  File "C:\Python 3.5\lib\site-packages\futuquant\open_context.py", line 644, in handle_read
    raise Exception("_AsyncNetworkManager : remote server close")
Exception: _AsyncNetworkManager : remote server close
_AsyncNetworkManager : remote server close

Traceback (most recent call last):
  File "C:\Python 3.5\lib\site-packages\futuquant\open_context.py", line 644, in handle_read
    raise Exception("_AsyncNetworkManager : remote server close")
Exception: _AsyncNetworkManager : remote server close
_AsyncNetworkManager : remote server close

Traceback (most recent call last):
  File "C:\Python 3.5\lib\site-packages\futuquant\open_context.py", line 644, in handle_read
    raise Exception("_AsyncNetworkManager : remote server close")
Exception: _AsyncNetworkManager : remote server close
_AsyncNetworkManager : remote server close

Traceback (most recent call last):
  File "C:\Python 3.5\lib\site-packages\futuquant\open_context.py", line 644, in handle_read
    raise Exception("_AsyncNetworkManager : remote server close")
Exception: _AsyncNetworkManager : remote server close
_AsyncNetworkManager : remote server close

Traceback (most recent call last):
  File "C:\Python 3.5\lib\site-packages\futuquant\open_context.py", line 644, in handle_read
    raise Exception("_AsyncNetworkManager : remote server close")
Exception: _AsyncNetworkManager : remote server close
_AsyncNetworkManager : remote server close

Traceback (most recent call last):
  File "C:\Python 3.5\lib\site-packages\futuquant\open_context.py", line 644, in handle_read
    raise Exception("_AsyncNetworkManager : remote server close")
Exception: _AsyncNetworkManager : remote server close
_AsyncNetworkManager : remote server close

Traceback (most recent call last):
  File "C:\Python 3.5\lib\site-packages\futuquant\open_context.py", line 644, in handle_read
    raise Exception("_AsyncNetworkManager : remote server close")
Exception: _AsyncNetworkManager : remote server close
_AsyncNetworkManager : remote server close

**Comment by zivzhou89** [comment]
有条件的话下载一个牛牛客户端，连接本地的客户端会更稳定。
如何下载及安装参考https://futunnopen.github.io/futuquant/setup/setup.html

**Comment by FutunnOpen** [comment]
建议使用 futuOpenD 新网关客户端  https://www.futunn.com/download/openAPI
