### ISSUE TITLE
Run futuquant/examples/learn/get_realtime_data.py 一直出現下面的問題

### ISSUE THREAD

**Issue by FelixChan29** [FutunnOpen/futuquant#86]
2018-06-19 17:26:47,678 [open_context_base.py] _socket_reconnect_and_wait_ready:289:  enter ...
2018-06-19 17:26:47,678 [sync_network_manager.py] reconnect:65:  ****
2018-06-19 17:26:47,678 [sync_network_manager.py] _socket_create_and_loop_connect:154: ***
2018-06-19 17:26:47,680 [open_context_base.py] notify_sync_socket_connected:367: sync socket init_connect
Traceback (most recent call last):
  File "C:\Users\shkfec\Desktop\futuquant-master\futuquant\common\sync_network_manager.py", line 109, in network_query
    recv_buf = self.s.recv(5 * 1024 * 1024)
socket.timeout: timed out
2018-06-19 17:26:57,685 [open_context_base.py] _sync_init_connect:69: init connect fail: ERROR. timed out when receiving after sending 136 bytes.
2018-06-19 17:26:57,685 [sync_network_manager.py] _socket_create_and_loop_connect:193: wait to connect FutuOpenD
2018-06-19 17:26:59,185 [open_context_base.py] notify_sync_socket_connected:367: sync socket init_connect
Traceback (most recent call last):
  File "C:\Users\shkfec\Desktop\futuquant-master\futuquant\common\sync_network_manager.py", line 109, in network_query
    recv_buf = self.s.recv(5 * 1024 * 1024)
socket.timeout: timed out
2018-06-19 17:27:09,187 [open_context_base.py] _sync_init_connect:69: init connect fail: ERROR. timed out when receiving after sending 136 bytes.
2018-06-19 17:27:09,187 [sync_network_manager.py] _socket_create_and_loop_connect:193: wait to connect FutuOpenD
2018-06-19 17:27:10,690 [open_context_base.py] notify_sync_socket_connected:367: sync socket init_connect
Traceback (most recent call last):
  File "C:\Users\shkfec\Desktop\futuquant-master\futuquant\common\sync_network_manager.py", line 109, in network_query
    recv_buf = self.s.recv(5 * 1024 * 1024)
socket.timeout: timed out
2018-06-19 17:27:20,693 [open_context_base.py] _sync_init_connect:69: init connect fail: ERROR. timed out when receiving after sending 136 bytes.
2018-06-19 17:27:20,694 [sync_network_manager.py] _socket_create_and_loop_connect:193: wait to connect FutuOpenD
2018-06-19 17:27:22,195 [open_context_base.py] notify_sync_socket_connected:367: sync socket init_connect
Traceback (most recent call last):
  File "C:\Users\shkfec\Desktop\futuquant-master\futuquant\common\sync_network_manager.py", line 109, in network_query
    recv_buf = self.s.recv(5 * 1024 * 1024)
socket.timeout: timed out
2018-06-19 17:27:32,199 [open_context_base.py] _sync_init_connect:69: init connect fail: ERROR. timed out when receiving after sending 136 bytes.
2018-06-19 17:27:32,200 [sync_network_manager.py] _socket_create_and_loop_connect:193: wait to connect FutuOpenD
2018-06-19 17:27:33,701 [open_context_base.py] notify_sync_socket_connected:367: sync socket init_connect
Traceback (most recent call last):
  File "C:\Users\shkfec\Desktop\futuquant-master\futuquant\common\sync_network_manager.py", line 109, in network_query
    recv_buf = self.s.recv(5 * 1024 * 1024)
socket.timeout: timed out
2018-06-19 17:27:43,703 [open_context_base.py] _sync_init_connect:69: init connect fail: ERROR. timed out when receiving after sending 136 bytes.
2018-06-19 17:27:43,703 [sync_network_manager.py] _socket_create_and_loop_connect:193: wait to connect FutuOpenD
2018-06-19 17:27:45,205 [open_context_base.py] notify_sync_socket_connected:367: sync socket init_connect
Traceback (most recent call last):
  File "C:\Users\shkfec\Desktop\futuquant-master\futuquant\common\sync_network_manager.py", line 109, in network_query
    recv_buf = self.s.recv(5 * 1024 * 1024)
socket.timeout: timed out
2018-06-19 17:27:55,208 [open_context_base.py] _sync_init_connect:69: init connect fail: ERROR. timed out when receiving after sending 136 bytes.
2018-06-19 17:27:55,209 [sync_network_manager.py] _socket_create_and_loop_connect:193: wait to connect FutuOpenD
2018-06-19 17:27:56,709 [open_context_base.py] notify_sync_socket_connected:367: sync socket init_connect

**Comment by FelixChan29** [comment]
get_realtime_data.py 內的東西沒有改動過
futu客戶端和FutuOpenD都一直在運行
其他example內的.py也是有同樣問題

**Comment by williamjie** [comment]
服务和机器重启试试吧，win很容易出现这种情况；

**Comment by loadatom** [comment]
最新的版本已经正常
